name: whatsapp_clone
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  country_picker: ^2.0.21
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.2

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash_light.png
  color_dark: "#111B21"
  image_dark: assets/images/splash_dark.png
  android_12:
    color: "#FFFFFF"
    image: assets/images/splash_light.png
    icon_background_color: "#FFFFFF"
    color_dark: "#111B21"
    image_dark: assets/images/splash_dark.png
    icon_background_color_dark: "#111B21"




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
